### ISSUE TITLE
Enable Chunk with ExposureTime

### ISSUE THREAD

**Issue by monzelr** [genicam/harvesters#176]
**Describe the bug**
After setting the chunk to enable and to activate the chunk mode with the chunkSeletor 'ExposureTime' I get an error in `ia.fetch_buffer()`.

**To Reproduce**
1. Run this code:
```
import os
import harvesters
print(harvesters.__version__)

import numpy as np
import cv2
from harvesters.core import Harvester
from genicam.gentl import TimeoutException

# configurations
imshowWidth = 1080
fps = 30.0
setChunk = True

h = Harvester()
# ATTENTION! Please use the CTI file in the original location!
path = os.path.abspath(r'C:\Program Files\Baumer GAPI SDK\Components\Bin\x64\bgapi2_usb.cti')
print(path)

h.add_cti_file(path)
h.update_device_info_list()
ia = h.create_image_acquirer(0)

ia.keep_latest = True
ia.num_filled_buffers_to_hold = 1

# Set chunk mode active / enable chunk / get exposure time in data packet
if setChunk:
    ia.remote_device.node_map.ChunkSelector.value = 'ExposureTime'
    ia.remote_device.node_map.ChunkEnable.value = True
    ia.remote_device.node_map.ChunkModeActive.value = True
print("ChunkSelector: " + str(ia.remote_device.node_map.ChunkSelector.value))
print("ChunkEnable: " + str(ia.remote_device.node_map.ChunkEnable.value))
print("ChunkModeActive: " + str(ia.remote_device.node_map.ChunkModeActive.value))

# Configure frame rate
ia.remote_device.node_map.AcquisitionFrameRateEnable.value = True
ia.remote_device.node_map.AcquisitionFrameRate.value = min(
    fps, ia.remote_device.node_map.AcquisitionFrameRate.max
)

# window
WINDOW_NAME = 'harvesters'
cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_GUI_NORMAL)

image = None
ia.start_acquisition()

while True:
    try:
        with ia.fetch_buffer() as buffer:
            component = buffer.payload.components[0]
            # Reshape and convert 2-dimensional to 3-dimensional array - Mono Camera!!
            image = cv2.cvtColor(component.data.copy().reshape(component.height, component.width), cv2.COLOR_GRAY2RGB)
            # resize to fit in imshow
            image = cv2.resize(image, (0, 0), fx=imshowWidth/component.width, fy=imshowWidth/component.width)
    except TimeoutException:
        print("Timeout ocurred waiting for image.")
    except ValueError as err:
        print(err)

    # Show the image if possible
    if image is not None:

        # resize window if necessary
        if image.shape[1] is not cv2.getWindowImageRect(WINDOW_NAME)[2] and \
                image.shape[0] is not cv2.getWindowImageRect(WINDOW_NAME)[3]:
            cv2.resizeWindow(WINDOW_NAME, image.shape[1], image.shape[0])

        # show image
        cv2.imshow(
            WINDOW_NAME,
            image,
        )

    # Keyboard handling
    keypress = cv2.waitKey(1)

    if keypress == 27 or cv2.getWindowProperty(WINDOW_NAME, cv2.WND_PROP_VISIBLE) < 1:
        #  # escape key pressed or window has been closed (x button clicked)
        break

cv2.destroyWindow(WINDOW_NAME)
if ia is not None:
    ia.stop_image_acquisition()
```

2. See error
```
C:\Users\monzelr\.conda\envs\genicam\python.exe D:/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT.py
1.2.1
C:\Program Files\Baumer GAPI SDK\Components\Bin\x64\bgapi2_usb.cti
ChunkSelector: ExposureTime
ChunkEnable: True
ChunkModeActive: True
Traceback (most recent call last):
  File "D:/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT.py", line 51, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 2639, in fetch_buffer
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 1170, in __init__
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 1303, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 1479, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 1402, in _build_component
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 846, in __init__
    symbolic = self.data_format
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters\core.py", line 1044, in data_format
    return dict_by_ints[self.data_format_value]
KeyError: 'Mono8'

Process finished with exit code 1
```

**Expected behavior**
see error. Also I expect additional data in payload object.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Python: 3.6.7
 - Harvester: 1.2.1
 - GenTL Producer: C:\Program Files\Baumer GAPI SDK\Components\Bin\x64\bgapi2_usb.cti
 - Camera: Baumer VCXU-23M

I was wondering if activating Chunk Data is allowed in harvesters, but I found this issue: https://github.com/genicam/harvesters/issues/33
Is it still allowed? If yes, could you please give me tips where to debug to find a solution?

**Comment by kazunarikudo** [comment]
@monzelr Hi, thank you for the report. Maybe this issue is related to issue #175. I have just created a branch `_issue_175`. Could you try that out to check if that resolves the issue you are facing, please? /Kazunari

**Comment by monzelr** [comment]
This fixes the `KeyError: 'Mono8'`. However, now I got another error, but this error looks like the camera does not support this feature... I am going to debug this. Maybe you also have another explanation?

Here is the error code:
```
C:\Users\monzelr\.conda\envs\genicam\python.exe D:/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT.py
_issue_175
C:\Program Files\Baumer GAPI SDK\Components\Bin\x64\bgapi2_usb.cti
ChunkSelector: ExposureTime
ChunkEnable: True
ChunkModeActive: True
Traceback (most recent call last):
  File "D:/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT.py", line 51, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 2569, in fetch_buffer
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1100, in __init__
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1233, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1409, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1332, in _build_component
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 834, in __init__
    self._data = self._to_np_array(proxy)
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 841, in _to_np_array
    nr_bytes = self._buffer.width * self._buffer.height
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\genicam-1.0.0-py3.6-win-amd64.egg\genicam\gentl.py", line 4368, in _get_width
    return _gentl.Buffer__get_width(self)
_gentl.NotImplementedException: GenTL exception: Requested operation not implemented. (Message from the source: Buffer info cmd 10 failed with -1003) (ID: -1003)

Process finished with exit code 1
```

**Comment by kazunarikudo** [comment]
Hi, I have just committed a fix. Would that resolve the issue?

**Comment by monzelr** [comment]
Hi @kazunarikudo 
this also does not solve the issue. Now I got a `ValueError: buffer is smaller than requested size`:

```
C:\Users\monzelr\.conda\envs\genicam\python.exe D:/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT.py
_issue_175
C:\Program Files\Baumer GAPI SDK\Components\Bin\x64\bgapi2_usb.cti
ChunkSelector: ExposureTime
ChunkEnable: True
ChunkModeActive: True
Traceback (most recent call last):
  File "D:/FA/software/$DATA_SVN/sourceCode/harvestersTestForGIT.py", line 51, in <module>
    with ia.fetch_buffer() as buffer:
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 2577, in fetch_buffer
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1108, in __init__
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1241, in _build_payload
    buffer=buffer, node_map=node_map, logger=logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1417, in __init__
    buffer=buffer, node_map=node_map
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 1340, in _build_component
    logger=self._logger
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 834, in __init__
    self._data = self._to_np_array(proxy)
  File "C:\Users\monzelr\.conda\envs\genicam\lib\site-packages\harvesters-_issue_175-py3.6.egg\harvesters\core.py", line 861, in _to_np_array
    offset=self.data_offset
ValueError: buffer is smaller than requested size

Process finished with exit code 1
```

When I debug, I don't see any data in the class `Component2DImage`:
![image](https://user-images.githubusercontent.com/60315601/84156321-a4b78500-aa69-11ea-823c-82219220b252.png)

**Comment by theytaz3** [comment]
I think I've found a way to get that information back. 
When I read my buffer, I use this line to retrieve my chunkTimestamp : 

![image](https://user-images.githubusercontent.com/33628286/86473326-ff7a8e80-bd40-11ea-87d3-90343cd631c2.png)

**Comment by kazunarikudo** [comment]
@theytaz3 Hi. That's the typical usage where the GenICam chunk data feature offers. /Kazunari

**Comment by monzelr** [comment]
Hi @theytaz3 and @kazunarikudo,

yes, thank you for responding to this issue, I totally forgot to post the solution. I already read the genapi documentation which tells about how to access the enabled chunks.
In my case it would be the nodes :
**ChunkExposureTime.value
ChunkGain.value**

However, I am still wondering why it takes so long to change the exposure time during image acquisition. My camera needs about 200ms to change the exposure time value from 11ms to 12 ms. I tried different ways too, like stopping the image acquisition, change exposure time and start the image acquisition again. But so far no success.

Here is a "simple" example code on how to modify the exposure time "as fast as possible" during image acquisition (use case: generate an auto exposure algorithm). Maybe someone has found a faster implementation!? As I said before, my camera needs around 200ms to change the exposure time. It would be nice if others could test the code to verify the problem, because maybe it is just my camera...

```
import os
import harvesters
print(harvesters.__version__)

import numpy as np
import cv2
from harvesters.core import Harvester
from harvesters.core import PayloadImage
from genicam.gentl import TimeoutException
from genicam.genapi import SingleChunkData
import time

from genicam import gentl

# gentl.DataStream.ds_get_buffer_chunk_data()

# _buffer._get_single_chunk_data_list() returns single chunk data
# single.ChunkID
# single.ChunkOffset
# single.ChunkLength
scd = SingleChunkData


# DSGetBufferInfo()
# BUFFER_INFO_CONTAINS_CHUNKDATA
# PAYLOAD_TYPE_CHUNK_DATA

# ia._update_chunk_data

# configurations
imshowWidth = 1080
fps = 30.0

h = Harvester()
# ATTENTION! Please use the CTI file in the original location!
path = os.path.abspath(r'C:\Program Files\Baumer GAPI SDK\Components\Bin\x64\bgapi2_usb.cti')
#path = os.path.abspath(r'C:\Program Files\Baumer GAPI SDK (64 Bit)\Components\Bin\bgapi2_usb.cti')
print(path)

h.add_cti_file(path)
h.update_device_info_list()
ia = h.create_image_acquirer(0)

ia.keep_latest = True
ia.num_filled_buffers_to_hold = 1

# Set chunk mode active / enable chunk / get exposure time in data packet
# ia.remote_device.node_map.ComponentSelector = 'Range'
# ia.remote_device.node_map.ComponentEnable.value = True

# Activate Chunk Mode
#if ia.remote_device.node_map.ChunkModeActive.
ia.remote_device.node_map.ChunkModeActive.value = True

ia.remote_device.node_map.ChunkSelector.value = 'Image'
ia.remote_device.node_map.ChunkEnable.value = True
ia.remote_device.node_map.ChunkSelector.value = 'ExposureTime'
ia.remote_device.node_map.ChunkEnable.value = True
ia.remote_device.node_map.ChunkSelector.value = 'Gain'
ia.remote_device.node_map.ChunkEnable.value = True

# window
WINDOW_NAME = 'harvesters'
cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_GUI_NORMAL)

image = None
ia.remote_device.node_map.ExposureTime.set_value(5000.0)
ia.start_acquisition()

start = time.time()
newExp = ia.remote_device.node_map.ExposureTime.value

setFlag = True

while True:
    try:
        with ia.fetch_buffer() as buffer:

            component = buffer.payload.components[0]
            # Reshape and convert 2-dimensional to 3-dimensional array - Mono Camera!!
            image = cv2.cvtColor(component.data.copy().reshape(component.height, component.width), cv2.COLOR_GRAY2RGB)
            # resize to fit in imshow
            image = cv2.resize(image, (0, 0), fx=imshowWidth/component.width, fy=imshowWidth/component.width)

            exposureTime = ia.remote_device.node_map.ChunkExposureTime.value
            gain = ia.remote_device.node_map.ChunkGain.value

        if newExp == exposureTime:
            end = time.time()
            newExp = exposureTime + 1000.0
            print(format(end-start, '3.3f') + ' s for exposure Time ' + str(exposureTime) + " / gain: " + str(gain))
            ia.remote_device.node_map.ExposureTime.set_value(newExp)
            start = time.time()
        else:
            print("exposure time: " + str(exposureTime))

    except TimeoutException:
        print("Timeout ocurred waiting for image.")
    except ValueError as err:
        print(err)

    # Show the image if possible
    if image is not None:

        # resize window if necessary
        if image.shape[1] is not cv2.getWindowImageRect(WINDOW_NAME)[2] and \
                image.shape[0] is not cv2.getWindowImageRect(WINDOW_NAME)[3]:
            cv2.resizeWindow(WINDOW_NAME, image.shape[1], image.shape[0])

        # show image
        cv2.imshow(
            WINDOW_NAME,
            image,
        )

    # Keyboard handling
    keypress = cv2.waitKey(1)

    if keypress == 27 or cv2.getWindowProperty(WINDOW_NAME, cv2.WND_PROP_VISIBLE) < 1:
        #  # escape key pressed or window has been closed (x button clicked)
        break

cv2.destroyWindow(WINDOW_NAME)
if ia is not None:
    ia.stop_image_acquisition()
```
