### ISSUE TITLE
Randomly appearing black lines in video

### ISSUE THREAD

**Issue by neelsbrink** [genicam/harvesters#188]
Hi Kazunari

I have been capturing and displaying images from a JAI BM-500 GE camera (Harvesters 1.2.1 and Python 3.6 (PyCharm)) successfully in Mono8 pixel format. When I change to Mono10 or Mono12, black lines appear randomly in the images despite using low frame rates (<10 fps). I then upgraded to Harvesters 1.2.6 in an attempt to see if it will help, but now the Mono10 and Mono12 results in an error:
_ValueError: cannot reshape array of size 3790836 into shape (2058,2456)_
because the number of elements is not 2456x2058:
_buffer: 2456 x 2058, Mono12, 3790836 elements_ 

What has changed in this regards from 1.2.1 and where can I look for resolving the black lines?
When I use the JAI control software the lines are absent.
Thank you
regards
Neels

Code:
_____________________________________________________________________________________________

    from harvesters.core import Harvester
    from numpy import *
    import numpy as np
    import cv2

    h = Harvester()

    h.add_cti_file(r'C:\Program Files\MATRIX VISION\mvIMPACT Acquire\bin\x64\mvGenTLProducer.cti')
    h.update_device_info_list()

    ia = h.create_image_acquirer(0) #camera nr 0

    pixelformat='Mono12'
    ia.remote_device.node_map.PixelFormat.set_value(pixelformat)

    #Start acquisition
    ia.start_image_acquisition()

    cv2.namedWindow('win1',cv2.WINDOW_FREERATIO)
    cv2.resizeWindow('win1',420,420)
    cv2.moveWindow('win1',10,500)

    while True:

    with ia.fetch_buffer() as buffer:

        component = buffer.payload.components[0]
        ncol=component.width
        nrow=component.height
        image = component.data.reshape(nrow, ncol)

        cv2.imshow('win1',(image)

        if cv2.waitKey(1) & 0xFF == ord('q'):
          break

    ia.destroy()
    cv2.destroyAllWindows()
    h.reset()

**Comment by kazunarikudo** [comment]
@neelsbrink Hi. Sounds like the buffer only has 2058 x 1842 elements, i.e., it's less than 398 lines/rows. I do not have another item that I can speak but could you show me the output from the following code, please?
```
    ...
    component = buffer.payload.components[0]
    print(component). # I want to see this.
    ncol=component.width
    nrow=component.height
    image = component.data.reshape(nrow, ncol)
    ...
```

**Comment by neelsbrink** [comment]
Hi Kazunari
print(component) produces:

2456 x 2058, Mono12, 3790836 elements,
[139 145 142 ... 226 227 224]

regards
Neels

**Comment by kazunarikudo** [comment]
@neelsbrink Hi, Neels. I'm working on it and will let you know once a candidate version turned available. Sorry for the inconvenience. /Kazunari

**Comment by kazunarikudo** [comment]
@neelsbrink Hi again. The fix has been committed to the branch `_issue_188`. Could you try that out and let me know if it fixes your issue when you can? I'm looking forward to hearing from you.

**Comment by neelsbrink** [comment]
Thanks Kazunari, the number of elements is correct now, but the black lines
still appear when using Mono10 or Mono12
regards

**Comment by kazunarikudo** [comment]
@neelsbrink Hi, Neels. Thank you for the update. Could you show me the image for example, please?

**Comment by kazunarikudo** [comment]
In addition, it would be very nice if you could check which pixel would be the beginning of the black line; for example, every black line begins at the `n`th pixel and end at the last pixel, etc.

**Comment by kazunarikudo** [comment]
One more question: Does the black line consist of only zero gray values?

**Comment by neelsbrink** [comment]
The black lines start and end at any place in the image randomly, have
varying lengths but the whole line has zero graylevels:


[image: image.png]

[image: image.png]

**Comment by kazunarikudo** [comment]
@neelsbrink Thank you, but the images you pasted above are displayed as follows:

>> [image: image.png]

Could you make another try, please?

**Comment by neelsbrink** [comment]
See attached

**Comment by kazunarikudo** [comment]
![95FD88F0-8143-4E64-A8EF-4AAB6CCCCF91](https://user-images.githubusercontent.com/8652625/87033656-95bb2280-c221-11ea-903a-8ba57618bc78.jpeg)

**Comment by kazunarikudo** [comment]
@neelsbrink Please see above. That’s what I’m seeing...

**Comment by kazunarikudo** [comment]
@neelsbrink (1) Does your camera support the `TestPattern` feature? If so, could you try to transmit a still pattern (a pattern that does not move) in either `Mono10` or `Mono12` and see what happens, please? I guess even if the camera transmits such a still image the black line would appear but I would like to see just for our information. (2) In addition, how do you check the black lines? Have you checked that on both a viewer and Harvester? I feel we need to make sure if where the black line appears in the data path. (3) Another thought I have is to test what happens if another camera transmits images in `Mono10` or `Mono12`.

**Comment by neelsbrink** [comment]
I hope the images are now visible. I can't see how to activate a test
pattern, waiting for JAI for a response whether it is possible. I check the
black lines by plotting a vertical profile across each live  image in
PyCharm and investigating the line values. Unfortunately I don't have
another camera.

**Comment by kazunarikudo** [comment]
@neelsbrink 

> I hope the images are now visible

Unfortunately, nothing has been displayed. How about you? Can you see the image in the comment cell where you possted?

By the way, as far as I tested, Harvester's unpacking/extracting feature does not alter any given data during the process. One thing I can say now is t's cumbersome...

>  I check the black lines by plotting a vertical profile across each live image in PyCharm and investigating the line values.

Would it be possible to paste the array values here? I do not care if it's just a part of the array. I just want to see a black line begins in an image.

**Comment by kazunarikudo** [comment]
@neelsbrink 

> I check the black lines by plotting a vertical profile across each live  image in PyCharm and investigating the line values

Where are you observing the data at? Right after the Harvester delivered the data? Or somewhere else in the OpenCV domain?

**Comment by neelsbrink** [comment]
I view the 8-bit data in OpenCV (see my code) but print the original data from
        image = component.data.reshape(nrow, ncol)

![image2](https://user-images.githubusercontent.com/13899456/87051077-65fb2300-c1ff-11ea-9201-ad8b832e18d1.jpg)
![image1](https://user-images.githubusercontent.com/13899456/87051095-6b586d80-c1ff-11ea-871d-f1a5d3f6fa8f.jpg)

image values along black line, frame1:
[1682 1653 1678 1672 1677 1684 1672 1682 1701 1689 1663 1671 1644 1671
 1690 1641 1725 1664 1620 1673 1666 1645 1654 1673 1729 1619 1697 1635
 1705 1669 1613 1665 1622 1663 1604 1661 1602 1628 1617 1687 1638 1667
 1605 1671 1664 1600 1668 1636 1614 1697    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0]

frame2:
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0 2052 2173 2086 2021 2160 2077 2068 2053
 2019 2032 2042 2064 2091 2148 2125 2108 2081 2090 2160 2190 2114 2119
 2079 2091 2141 2137 2126 2198 2090 2174 2171 2092 2060 2162 2095 2150
 2189 2119]

**Comment by neelsbrink** [comment]
I have just managed to get a test pattern, and the lines are there as well
![testpattern](https://user-images.githubusercontent.com/13899456/87061132-a95b8e80-c20b-11ea-9703-f07036d7f255.jpg)

**Comment by kazunarikudo** [comment]
@neelsbrink Thank you!

**Comment by kazunarikudo** [comment]
@neelsbrink Regarding the 3rd image, even if you transmit the test pattern, the black lines are moving every frame?

**Comment by kazunarikudo** [comment]
@neelsbrink I would appreciate if you could show me the test pattern that consists of a single gray level.

**Comment by kazunarikudo** [comment]
@neelsbrink Regarding the 3rd image, I can confirm (1) there are lines that consist of multiple gray values. (2) In addition, some lines are being interfered with the test pattern; you showed a line that consists of all zero gray value but the lines that I am talking about look like consisting of several gray levels, and they look get interfered by the test pattern in the background. Do you think they are just a digital noise that are produced while it's converted to a JPEG file?

<img width="827" alt="Screen Shot 2020-07-10 at 1 10 41" src="https://user-images.githubusercontent.com/8652625/87064321-83a1aa00-c24a-11ea-91fc-6028545940e4.png">

**Comment by neelsbrink** [comment]
I think it is the result of the conversion. I saved the image data to 16-bit TIFF and could verify that the lines are 0 graylevel. I can't upload the .tif and don't know how else to show an un-altered image of the lines.   The included histogram  shows no other graylevels close to 0, only  > 1500
![histo](https://user-images.githubusercontent.com/13899456/87071271-48878280-c21a-11ea-877b-ec96f1b93e1d.jpg)

**Comment by thiesmoeller** [comment]
Can you increase the interpacket delay  of your device?  Feature GevSCPD.
The error looks like lost packets. Which are not aligned to line length and thus appear "randomly" in your image.

**Comment by kazunarikudo** [comment]
@thiesmoeller Wow, my familiar hero showed up! :-) Thank you very much for your suggestion. That is VERY promising! (I will write a message to you later because I want to say hello and some more!)

@neelsbrink As Thies suggested, please try to increase that value. `Mono10` or `Mono12` doubles the data amount to be transmitted compared to `Mono8` then they tend to choke up the receiver and the "choke up" appears as packet loss and it can be seen as a consecutive blank (the number of blank data is defined by the packet size in general). Actually you are trying to transmit 4M pixels images. That truly is the condition where it's worth checking the way Thies kindly suggested.

**Comment by neelsbrink** [comment]
Thanks Thies and Kazinaru. The increased interpacket delay does reduce (not remove completely) the number of black lines, but I have to increase it to > 5000 to have an effect. This means delays in the image upon movement.  I am also starting to see the lines when using Mono8, although not when using the JAI control kit.

**Comment by kazunarikudo** [comment]
@neelsbrink  How large is the size of a packet? /**Kazunari**

**Comment by neelsbrink** [comment]
4036 which is the  max I can set it at

**Comment by kazunarikudo** [comment]
@neelsbrink There is a NIC that offers you 9k or more. How about trying them out?

**Comment by keck-in-space** [comment]
Hello, sorry to resurrect this issue but I am seeing the same problem on a FLIR ORYX camera. Is there some way to detect that there were missing packets in the image? I am OK with throwing away incomplete images for my application. Thanks!
