### ISSUE TITLE
XML parser error

### ISSUE THREAD

**Issue by Impstar314** [genicam/harvesters#207]
_setup description:_
Matrox Rapixo frame grabber card (dual input *not* quad).
Adimec TMX74 Coaxpress camera.
installed on computer Matrox MIL 10, SP4, update 87. when checked - the firmwareupdater states that the frame grabber is up to date. Continuous acquisition is possible using Matrox's intellicam app (certain that the camera is fine and works properly)
i'm using the Spyder IDE through anaconda, running on python 3.7.6 (conda base).

_problem statement:_
Whenever I try to run my code (attached below) I keep getting a RuntimeException from an XmlParser.cpp file. I think it fails reading the ® symbol somewhere. The error:

![image](https://user-images.githubusercontent.com/73643249/97562820-ee8a1300-19ea-11eb-8fbd-274ae7e82c21.png)

when i go to the relevant place in the XML file i see:
![image](https://user-images.githubusercontent.com/73643249/97562354-293f7b80-19ea-11eb-8175-8c817c60835a.png)

I expected from my code to grab and save 10 images from the camera. instead, it saves 10 completely black images.
I can't seem to understand if the problem is somewhere in the harvesters module, the Matrox environment (the .cti file) or something else entirely.
Would greatly appreciate some help. thanks in advance :)
my code: 

[temp.txt](https://github.com/genicam/harvesters/files/5458049/temp.txt)

 - OS: windows 10
 - Python: 3.7.6
 - Harvester: 1.2.8
 - GenTL Producer: Matrox
 - Camera: Adimec tmx74 coaxpress

**Comment by divyasaxenaa** [comment]
Did you get any solution? I am facing same kind of issue.
Error while parsing XML stream at line 1 and column 2 : 'not well-formed (invalid token)' : RuntimeException thrown (file 'XmlParser.cpp', line 1720)

**Comment by Impstar314** [comment]
hi
once i installed the genicam module it solved my issues

**Comment by divyasaxenaa** [comment]
I have already installed genicam. I think in my case it’s not reading xml file from one of the  zip folder.

**Comment by superted6851** [comment]
**Describe the bug:**

XML parser issue due to "-en" token in XML file. Likely the genicam XML parser needs some error handling for unknown tokens or the XML files need correcting to remove the token. Not sure who the maintainer for the genicam module is as I could not find it on GitHub to post the issue there.

The other thing is the camera seems to use custom tl_type but is connected with a U3V interface, is there away to force the tl_type not sure if it would load different XML files then. 

(id_='MQ042MG-CM-TG (37060850)', vendor='XIMEA GmbH.', model='MQ042MG-CM-TG', tl_type='Custom', user_defined_name=None, serial_number='37060850', version='V4.21.20.00')

**To Reproduce:**
Steps to reproduce the behavior:

_harvester = Harvester()
_harvester.add_file("../../Viserion_NFBP/nfbp/devices/camera/genTL/libXIMEA_GenTL.cti")
_harvester.update()

ia = _harvester.create_image_acquirer(serial_number='37060850')

**This is the console output:**

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/1327683/108306763-d2072600-71e7-11eb-8326-be192e04e682.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/1327683/108307464-c405d500-71e8-11eb-9a2e-1ed7081605bc.png">



**Desktop (please complete the following information):**

OS: MacOS 11.1
Python: 3.8
Harvester: 1.2.8
GenTL Producer: Ximea
Camera: MQ042MG-CM-TG

**Comment by kazunarikudo** [comment]
I suspect the root cause being discussed here under the topic must be the same as ticket #226. Nothing has been concluded yet but this issue could turn out an issue that needs to be discussed by the GenICam committee. I will try to keep you all up to date. Thanks, Kazunari.

**Comment by Impstar314** [comment]
Thanks!

**Comment by kazunarikudo** [comment]
@superted6851, @divyasaxenaa, and @Impstar314 Hi, probably the latest commit at ff862dea22a1eb53610417a3d8f9e2c39c680509 should fix the issue. I would highly appreciate it if you could try it out when you can. Thank you. Best regards, Kazunari.

**Comment by superted6851** [comment]
@kazunarikudo I still get the same error but now it returns an image acquirer so I am able to capture one frame but then it throws an error message when I try to close the stream.

OS: MacOS 11.3.1
Python: 3.8
Harvester: 1.3.1.post.dev5
GenTL Producer: Ximea
Camera: MQ042MG-CM-TG

**Console Output**

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/1327683/119102062-38504e80-ba4c-11eb-8fb4-58848e3fbc94.png">


**Test image output**

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1327683/119102342-806f7100-ba4c-11eb-9093-482cc4b34643.png">

**Comment by kazunarikudo** [comment]
@superted6851 Thank you for giving it a try. Could you give me the `GenTL_Stream.xml` file, please? It should be located somewhere under the `/var` directory. I believe the directory itself is alive until the machine is rebooted. Thanks, Kazunari.

**Comment by superted6851** [comment]
@kazunarikudo  Here it is
[GenTL_Stream.TXT](https://github.com/genicam/harvesters/files/6522904/GenTL_Stream.TXT)

**Comment by kazunarikudo** [comment]
@superted6851 Hi, could you give it a try for the latest commit in the master? I have added a feature to the `ImageAcquire` class so that you can specify the file name pattern and a sequence of data that is used as the beginning of garbage to be dropped/truncated. For your case, give it the following code if you are sure the linked camera causes the issue discussed here; the `file_dict` is optional so it is not necessary to pass a `dict` if you are sure the linked camera or the GenTL Producer does not cause any exception:
```
ia = h.create_image_acquirer(
    # no change here, use this parameter as you have used before:
    0,
    # pass it a dict consists of a key and a value, a regular expression pattern
    # for a file name to be applied the data truncation and a marker data,
    # respectively:
    file_dict={r'GenTL_Stream\.xml': bytes('-en', encoding='utf-8')})
```
The `ImageAcquire` object will drop/truncate the sequence that begins as `-en` if the file name is `GenTL_Stream.xml`. Having dropped the garbage data, that you have seen as `-en`, the XML parser can start to handle a valid XML file at last.

**Comment by superted6851** [comment]
@kazunarikudo Still getting the same error seems file_dict is not working as expected.

OS: MacOS 11.3.1
Python: 3.8
Harvester: 1.3.1.post.dev12
GenTL Producer: Ximea
Camera: MQ042MG-CM-TG

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1327683/120132378-d8e90000-c1fc-11eb-9c76-cca639f2a914.png">
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/1327683/120132419-e9997600-c1fc-11eb-8697-3b684cea645f.png">

**Comment by kazunarikudo** [comment]
@superted6851 Hi. Your case needs to have `r'GenTL_.+\.xml'` actually. The target seems to have the garbage in other files.
